apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      initContainers:
        - name: run-migrations
          image: registry.digitalocean.com/firebrick/core:latest # Use the same image as the application
          command:
            - sh
            - "-c"
            - |
              echo "Running migrations...";
              npm run prisma:migrate;
              echo "Migrations completed.";
      containers:
        
        - name: core
          image: registry.digitalocean.com/firebrick/core:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: DATABASE_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: GOOGLE_REDIRECT_URI
            - name: MS_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: MS_REDIRECT_URI
            - name: MS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: MS_CLIENT_ID
            - name: MS_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: MS_TENANT_ID
            - name: MS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-env-secrets
                  key: MS_CLIENT_SECRET
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "4"

---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    app: core
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
