apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: default # Use appropriate namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui # Container name must match in `kubectl set image`
          image: registry.digitalocean.com/firebrick/ui:latest # Placeholder, updated by GitHub Action
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
